package com.structurecraft.list;

public class namelist {

	public static String[] mcvariants = { "stone", "granite", "polished_granite", "diorite", "polished_diorite",
			"andesite", "polished_andesite", "grass_block", "dirt", "coarse_dirt", "podzol", "cobblestone",
			"oak_planks", "spruce_planks", "birch_planks", "jungle_planks", "acacia_planks", "dark_oak_planks",
			"bedrock", "sand", "red_sand", "gravel", "gold_ore", "deepslate_gold_ore", "iron_ore", "deepslate_iron_ore",
			"coal_ore", "deepslate_coal_ore", "nether_gold_ore", "oak_log", "spruce_log", "birch_log", "jungle_log",
			"acacia_log", "dark_oak_log", "stripped_spruce_log", "stripped_birch_log", "stripped_jungle_log",
			"stripped_acacia_log", "stripped_dark_oak_log", "stripped_oak_log", "oak_wood", "spruce_wood", "birch_wood",
			"jungle_wood", "acacia_wood", "dark_oak_wood", "stripped_oak_wood", "stripped_spruce_wood",
			"stripped_jungle_wood", "stripped_acacia_wood", "stripped_dark_oak_wood", "oak_leaves", "spruce_leaves",
			"birch_leaves", "jungle_leaves", "acacia_leaves", "dark_oak_leaves", "azalea_leaves",
			"flowering_azalea_leaves", "sponge", "wet_sponge", "glass", "lapis_ore", "deepslate_lapis_ore",
			"lapis_block", "sandstone", "chiseled_sandstone", "cut_sandstone", "note_block", "white_wool",
			"orange_wool", "magenta_wool", "light_blue_wool", "yellow_wool", "lime_wool", "pink_wool", "gray_wool",
			"light_gray_wool", "cyan_wool", "purple_wool", "blue_wool", "brown_wool", "green_wool", "red_wool",
			"black_wool", "gold_block", "iron_block", "bricks", "mossy_cobblestone", "obsidian", "spawner",
			"diamond_ore", "deepslate_diamond_ore", "diamond_block", "farmland", "redstone_ore",
			"deepslate_redstone_ore", "ice", "snow", "clay", "jukebox", "pumpkin_side", "netherrack", "soul_sand",
			"soul_soil", "basalt", "polished_basalt", "glowstone", "carved_pumpkin", "jack_o_lantern",
			"white_stained_glass", "orange_stained_glass", "magenta_stained_glass", "light_blue_stained_glass",
			"yellow_stained_glass", "lime_stained_glass", "pink_stained_glass", "gray_stained_glass",
			"light_gray_stained_glass", "cyan_stained_glass", "purple_stained_glass", "blue_stained_glass",
			"brown_stained_glass", "green_stained_glass", "red_stained_glass", "black_stained_glass", "stone_bricks",
			"mossy_stone_bricks", "cracked_stone_bricks", "chiseled_stone_bricks", "brown_mushroom_block",
			"red_mushroom_block", "mushroom_stem", "melon_side", "mycelium", "nether_bricks", "end_stone",
			"redstone_lamp", "emerald_ore", "deepslate_emerald_ore", "emerald_block", "redstone_block",
			"nether_quartz_ore", "quartz_block_top", "chiseled_quartz_block", "quartz_pillar_top", "white_terracotta",
			"orange_terracotta", "magenta_terracotta", "light_blue_terracotta", "yellow_terracotta", "lime_terracotta",
			"pink_terracotta", "gray_terracotta", "light_gray_terracotta", "cyan_terracotta", "purple_terracotta",
			"blue_terracotta", "brown_terracotta", "green_terracotta", "red_terracotta", "black_terracotta",
			"slime_block", "prismarine", "prismarine_bricks", "dark_prismarine", "sea_lantern", "hay_block",
			"smooth_stone", "sandstone_top", "quartz_block_bottom", "red_sandstone_top", "dirt_path", "magma",
			"nether_wart_block", "red_nether_bricks", "bone_block", "white_glazed_terracotta",
			"orange_glazed_terracotta", "magenta_glazed_terracotta", "light_blue_glazed_terracotta",
			"yellow_glazed_terracotta", "lime_glazed_terracotta", "pink_glazed_terracotta", "gray_glazed_terracotta",
			"light_gray_glazed_terracotta", "cyan_glazed_terracotta", "purple_glazed_terracotta",
			"blue_glazed_terracotta", "brown_glazed_terracotta", "green_glazed_terracotta", "red_glazed_terracotta",
			"black_glazed_terracotta", "white_concrete", "orange_concrete", "magenta_concrete", "light_blue_concrete",
			"yellow_concrete", "lime_concrete", "pink_concrete", "gray_concrete", "light_gray_concrete",
			"cyan_concrete", "purple_concrete", "blue_concrete", "brown_concrete", "green_concrete", "red_concrete",
			"black_concrete", "white_concrete_powder", "orange_concrete_powder", "magenta_concrete_powder",
			"light_blue_concrete_powder", "yellow_concrete_powder", "lime_concrete_powder", "pink_concrete_powder",
			"gray_concrete_powder", "light_gray_concrete_powder", "cyan_concrete_powder", "purple_concrete_powder",
			"blue_concrete_powder", "brown_concrete_powder", "green_concrete_powder", "red_concrete_powder",
			"black_concrete_powder", "dried_kelp_block", "dead_tube_coral_block", "dead_brain_coral_block",
			"dead_bubble_coral_block", "dead_fire_coral_block", "dead_horn_coral_block", "tube_coral_block",
			"brain_coral_block", "bubble_coral_block", "fire_coral_block", "horn_coral_block", "blue_ice",
			"warped_stem", "stripped_warped_stem", "warped_hyphae", "stripped_warped_hyphae", "warped_nylium",
			"warped_wart_block", "crimson_stem", "stripped_crimson_stem", "crimson_hyphae", "stripped_crimson_hyphae",
			"crimson_nylium", "shroomlight", "crimson_planks", "warped_planks", "target_side", "honey_block",
			"honeycomb_block", "netherite_block", "crying_obsidian", "blackstone", "polished_blackstone",
			"polished_blackstone_bricks", "cracked_polished_blackstone_bricks", "chiseled_polished_blackstone",
			"gilded_blackstone", "chiseled_nether_bricks", "cracked_nether_bricks", "quartz_bricks", "amethyst_block",
			"budding_amethyst", "tuff", "calcite", "tinted_glass", "powder_snow", "oxidized_copper", "weathered_copper",
			"exposed_copper", "copper_block", "copper_ore", "deepslate_copper_ore", "oxidized_cut_copper",
			"weathered_cut_copper", "exposed_cut_copper", "cut_copper", "waxed_copper_block", "waxed_weathered_copper",
			"waxed_exposed_copper", "waxed_oxidized_copper", "waxed_oxidized_cut_copper", "waxed_weathered_cut_copper",
			"waxed_exposed_cut_copper", "waxed_cut_copper", "dripstone_block", "moss_block", "rooted_dirt", "deepslate",
			"cobbled_deepslate", "polished_deepslate", "deepslate_tiles", "deepslate_bricks", "chiseled_deepslate",
			"cracked_deepslate_bricks", "cracked_deepslate_tiles", "smooth_basalt", "raw_iron_block",
			"raw_copper_block", "raw_gold_block", "ancient_debris", "red_sandstone", "chiseled_red_sandstone",
			"cut_red_sandstone", "packed_ice", "terracotta", "purpur_block", "purpur_pillar", "coal_block",
			"stripped_birch_wood", "bookshelf", "end_stone_bricks", "purpur_pillar_top", "quartz_pillar",
			"dirt_path_top", "mycelium_top", "podzol_top", "grass_block_top", "basalt_side", "polished_basalt_side",
			"hay_block_top", "bone_block_side", "ancient_debris_side" };
}
