package com.structurecraft.register;

import com.structurecraft.structurecraft;
import com.structurecraft.blocks.SlopeOBJBlock;
import com.structurecraft.blocks.SlopeOBJGlassBlock;
import com.structurecraft.list.namelist;
import com.structurecraft.list.properties;
import com.structurecraft.list.tablist;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fmllegacy.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

@Mod.EventBusSubscriber(modid = structurecraft.MODID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class blockgen {
	
	// experimentalForgeLightPipelineEnabled = true | in forge-client.toml  fixes the lighting of custom models!! | for OBJ files |
	
	public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, structurecraft.MODID);
	
	public static final RegistryObject<Block> SLOPEOBJ_STONE = BLOCKS.register("slopeobj_stone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GRANITE = BLOCKS.register("slopeobj_granite", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_POLISHED_GRANITE = BLOCKS.register("slopeobj_polished_granite", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DIORITE = BLOCKS.register("slopeobj_diorite", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> POLISHED_DIORITE = BLOCKS.register("slopeobj_polished_diorite", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ANDESITE = BLOCKS.register("slopeobj_andesite", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_POLISHED_ANDESITE = BLOCKS.register("slopeobj_polished_andesite", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MAIN = BLOCKS.register(namelist.SLOPEOBJ_MAIN, () -> new SlopeOBJBlock(Blocks.COBBLESTONE.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BEDROCK = BLOCKS.register("slopeobj_bedrock", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LAPIS_ORE = BLOCKS.register("slopeobj_lapis_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE_LAPIS_ORE = BLOCKS.register("slopeobj_deepslate_lapis_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_NETHERRACK = BLOCKS.register("slopeobj_netherrack", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BASALT = BLOCKS.register("slopeobj_basalt", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_POLISHED_BASALT = BLOCKS.register("slopeobj_polished_basalt", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLACKSTONE = BLOCKS.register("slopeobj_blackstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_POLISHED_BLACKSTONE = BLOCKS.register("slopeobj_polished_blackstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_POLISHED_BLACKSTONE_BRICKS = BLOCKS.register("slopeobj_polished_blackstone_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CRACKED_POLISHED_BLACKSTONE_BRICKS = BLOCKS.register("slopeobj_cracked_polished_blackstone_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CHISELED_POLISHED_BLACKSTONE = BLOCKS.register("slopeobj_chiseled_polished_blackstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GILDED_BLACKSTONE = BLOCKS.register("slopeobj_gilded_blackstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_TUFF = BLOCKS.register("slopeobj_tuff", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CALCITE = BLOCKS.register("slopeobj_calcite", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DRIPSTONE_BLOCK = BLOCKS.register("slopeobj_dripstone_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE = BLOCKS.register("slopeobj_deepslate", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_COBBLED_DEEPSLATE = BLOCKS.register("slopeobj_cobbled_deepslate", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_POLISHED_DEEPSLATE = BLOCKS.register("slopeobj_polished_deepslate", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE_TILES = BLOCKS.register("slopeobj_deepslate_tiles", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE_BRICKS = BLOCKS.register("slopeobj_deepslate_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CHISELED_DEEPSLATE = BLOCKS.register("slopeobj_chiseled_deepslate", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SMOOTH_BASALT = BLOCKS.register("slopeobj_smooth_basalt", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));

	public static final RegistryObject<Block> SLOPEOBJ_GOLD_ORE = BLOCKS.register("slopeobj_gold_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE_GOLD_ORE = BLOCKS.register("slopeobj_deepslate_gold_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_IRON_ORE = BLOCKS.register("slopeobj_iron_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE_IRON_ORE = BLOCKS.register("slopeobj_deepslate_iron_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_COAL_ORE = BLOCKS.register("slopeobj_coal_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE_COAL_ORE = BLOCKS.register("slopeobj_deepslate_coal_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_NETHER_GOLD_ORE = BLOCKS.register("slopeobj_nether_gold_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DIAMOND_ORE = BLOCKS.register("slopeobj_diamond_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE_DIAMOND_ORE = BLOCKS.register("slopeobj_deepslate_diamond_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_EMERALD_ORE = BLOCKS.register("slopeobj_emerald_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE_EMERALD_ORE = BLOCKS.register("slopeobj_deepslate_emerald_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_NETHER_QUARTZ_ORE = BLOCKS.register("slopeobj_nether_quartz_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_COPPER_ORE = BLOCKS.register("slopeobj_copper_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEEPSLATE_COPPER_ORE = BLOCKS.register("slopeobj_deepslate_copper_ore", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RAW_IRON_BLOCK = BLOCKS.register("slopeobj_raw_iron_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RAW_COPPER_BLOCK = BLOCKS.register("slopeobj_raw_copper_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RAW_GOLD_BLOCK = BLOCKS.register("slopeobj_raw_gold_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));

	public static final RegistryObject<Block> SLOPEOBJ_GRASS_BLOCK = BLOCKS.register("slopeobj_grass_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GRASS_BLOCK_COMPLETE = BLOCKS.register("slopeobj_grass_block_m", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DIRT = BLOCKS.register("slopeobj_dirt", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_COARSE_DIRT = BLOCKS.register("slopeobj_coarse_dirt", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PODZOL = BLOCKS.register("slopeobj_podzol", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PODZOL_COMPLETE = BLOCKS.register("slopeobj_podzol_m", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SAND = BLOCKS.register("slopeobj_sand", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_SAND = BLOCKS.register("slopeobj_red_sand", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GRAVEL = BLOCKS.register("slopeobj_gravel", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SOUL_SAND = BLOCKS.register("slopeobj_soul_sand", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SOUL_SOIL = BLOCKS.register("slopeobj_soul_soil", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MYCELIUM = BLOCKS.register("slopeobj_mycelium", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MYCELIUM_M = BLOCKS.register("slopeobj_mycelium_m", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DIRT_PATH = BLOCKS.register("slopeobj_dirt_path", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_FARMLAND = BLOCKS.register("slopeobj_farmland", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MOSS_BLOCK = BLOCKS.register("slopeobj_moss_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ROOTED_DIRT = BLOCKS.register("slopeobj_rooted_dirt", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));

	public static final RegistryObject<Block> SLOPEOBJ_OAK_PLANKS = BLOCKS.register("slopeobj_oak_planks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SPRUCE_PLANKS = BLOCKS.register("slopeobj_spruce_planks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BIRCH_PLANKS = BLOCKS.register("slopeobj_birch_planks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_JUNGLE_PLANKS = BLOCKS.register("slopeobj_jungle_planks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ACACIA_PLANKS = BLOCKS.register("slopeobj_acacia_planks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DARK_OAK_PLANKS = BLOCKS.register("slopeobj_dark_oak_planks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_OAK_LOG = BLOCKS.register("slopeobj_oak_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SPRUCE_LOG = BLOCKS.register("slopeobj_spruce_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BIRCH_LOG = BLOCKS.register("slopeobj_birch_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_JUNGLE_LOG = BLOCKS.register("slopeobj_jungle_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ACACIA_LOG = BLOCKS.register("slopeobj_acacia_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DARK_OAK_LOG = BLOCKS.register("slopeobj_dark_oak_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_SPRUCE_LOG = BLOCKS.register("slopeobj_stripped_spruce_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_BIRCH_LOG = BLOCKS.register("slopeobj_stripped_birch_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_JUNGLE_LOG = BLOCKS.register("slopeobj_stripped_jungle_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_ACACIA_LOG = BLOCKS.register("slopeobj_stripped_acacia_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_DARK_OAK_LOG = BLOCKS.register("slopeobj_stripped_dark_oak_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_OAK_LOG = BLOCKS.register("slopeobj_stripped_oak_log", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_OAK_WOOD = BLOCKS.register("slopeobj_oak_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SPRUCE_WOOD = BLOCKS.register("slopeobj_spruce_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BIRCH_WOOD = BLOCKS.register("slopeobj_birch_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_JUNGLE_WOOD = BLOCKS.register("slopeobj_jungle_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ACACIA_WOOD = BLOCKS.register("slopeobj_acacia_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DARK_OAK_WOOD = BLOCKS.register("slopeobj_dark_oak_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_OAK_WOOD = BLOCKS.register("slopeobj_stripped_oak_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_SPRUCE_WOOD = BLOCKS.register("slopeobj_stripped_spruce_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_BIRCH_WOOD = BLOCKS.register("slopeobj_stripped_birch_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_JUNGLE_WOOD = BLOCKS.register("slopeobj_stripped_jungle_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_ACACIA_WOOD = BLOCKS.register("slopeobj_stripped_acacia_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_DARK_OAK_WOOD = BLOCKS.register("slopeobj_stripped_dark_oak_wood", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));

	public static final RegistryObject<Block> SLOPEOBJ_WARPED_STEM = BLOCKS.register("slopeobj_warped_stem", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_WARPED_STEM = BLOCKS.register("slopeobj_stripped_warped_stem", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_WARPED_HYPHAE = BLOCKS.register("slopeobj_warped_hyphae", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_WARPED_HYPHAE = BLOCKS.register("slopeobj_stripped_warped_hyphae", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_WARPED_NYLIUM = BLOCKS.register("slopeobj_warped_nylium", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_WARPED_WART_BLOCK = BLOCKS.register("warped_wart_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CRIMSON_STEM = BLOCKS.register("slopeobj_crimson_stem", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_CRIMSON_STEM = BLOCKS.register("slopeobj_stripped_crimson_stem", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CRIMSON_HYPHAE = BLOCKS.register("slopeobj_crimson_hyphae", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STRIPPED_CRIMSON_HYPHAE = BLOCKS.register("slopeobj_stripped_crimson_hyphae", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CRIMSON_NYLIUM = BLOCKS.register("slopeobj_crimson_nylium", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CRIMSON_PLANKS = BLOCKS.register("slopeobj_crimson_planks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_WARPED_PLANKS = BLOCKS.register("slopeobj_warped_planks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	
	public static final RegistryObject<Block> SLOPEOBJ_GLASS = BLOCKS.register("slopeobj_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertieglass()));
	public static final RegistryObject<Block> SLOPEOBJ_WHITE_STAINED_GLASS = BLOCKS.register("slopeobj_white_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ORANGE_STAINED_GLASS = BLOCKS.register("slopeobj_orange_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MAGENTA_STAINED_GLASS = BLOCKS.register("slopeobj_magenta_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_BLUE_STAINED_GLASS = BLOCKS.register("slopeobj_light_blue_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_YELLOW_STAINED_GLASS = BLOCKS.register("slopeobj_yellow_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIME_STAINED_GLASS = BLOCKS.register("slopeobj_lime_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PINK_STAINED_GLASS = BLOCKS.register("slopeobj_pink_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GRAY_STAINED_GLASS = BLOCKS.register("slopeobj_gray_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_GRAY_STAINED_GLASS = BLOCKS.register("slopeobj_light_gray_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CYAN_STAINED_GLASS = BLOCKS.register("slopeobj_cyan_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PURPLE_STAINED_GLASS = BLOCKS.register("slopeobj_purple_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLUE_STAINED_GLASS = BLOCKS.register("slopeobj_blue_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BROWN_STAINED_GLASS = BLOCKS.register("slopeobj_brown_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GREEN_STAINED_GLASS = BLOCKS.register("slopeobj_green_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_STAINED_GLASS = BLOCKS.register("slopeobj_red_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLACK_STAINED_GLASS = BLOCKS.register("slopeobj_black_stained_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_TINTED_GLASS = BLOCKS.register("slopeobj_tinted_glass", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));

	public static final RegistryObject<Block> SLOPEOBJ_WHITE_WOOL = BLOCKS.register("slopeobj_white_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ORANGE_WOOL = BLOCKS.register("slopeobj_orange_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MAGENTA_WOOL = BLOCKS.register("slopeobj_magenta_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_BLUE_WOOL = BLOCKS.register("slopeobj_light_blue_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_YELLOW_WOOL = BLOCKS.register("slopeobj_yellow_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIME_WOOL = BLOCKS.register("slopeobj_lime_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PINK_WOOL = BLOCKS.register("slopeobj_pink_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GRAY_WOOL = BLOCKS.register("slopeobj_gray_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_GRAY_WOOL = BLOCKS.register("slopeobj_light_gray_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CYAN_WOOL = BLOCKS.register("slopeobj_cyan_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PURPLE_WOOL = BLOCKS.register("slopeobj_purple_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLUE_WOOL = BLOCKS.register("slopeobj_blue_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BROWN_WOOL = BLOCKS.register("slopeobj_brown_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GREEN_WOOL = BLOCKS.register("slopeobj_green_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_WOOL = BLOCKS.register("slopeobj_red_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLACK_WOOL = BLOCKS.register("slopeobj_black_wool", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	
	public static final RegistryObject<Block> SLOPEOBJ_LAPIS_BLOCK = BLOCKS.register("slopeobj_lapis_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GOLD_BLOCK = BLOCKS.register("slopeobj_gold_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_IRON_BLOCK = BLOCKS.register("slopeobj_iron_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DIAMOND_BLOCK = BLOCKS.register("slopeobj_diamond_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_OBSIDIAN = BLOCKS.register("slopeobj_obsidian", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MOSSY_COBBLESTONE = BLOCKS.register("slopeobj_mossy_cobblestone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_STONE_BRICKS = BLOCKS.register("slopeobj_stone_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MOSSY_STONE_BRICKS = BLOCKS.register("slopeobj_mossy_stone_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CRACKED_STONE_BRICKS = BLOCKS.register("slopeobj_cracked_stone_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CHISELED_STONE_BRICKS = BLOCKS.register("slopeobj_chiseled_stone_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_END_STONE = BLOCKS.register("slopeobj_end_stone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_REDSTONE_LAMP = BLOCKS.register("slopeobj_redstone_lamp", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_EMERALD_BLOCK = BLOCKS.register("slopeobj_emerald_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_QUARTZ_BLOCK = BLOCKS.register("slopeobj_quartz_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CHISELED_QUARTZ_BLOCK = BLOCKS.register("slopeobj_chiseled_quartz_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_QUARTZ_PILLAR = BLOCKS.register("slopeobj_quartz_pillar", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_QUARTZ_PILLAR_M = BLOCKS.register("slopeobj_quartz_pillar_m", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SMOOTH_STONE = BLOCKS.register("slopeobj_smooth_stone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SMOOTH_QUARTZ = BLOCKS.register("slopeobj_smooth_quartz", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PURPUR_BLOCK = BLOCKS.register("slopeobj_purpur_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PURPUR_PILLAR = BLOCKS.register("slopeobj_purpur_pillar", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PURPUR_PILLAR_M = BLOCKS.register("slopeobj_purpur_pillar_m", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_FROSTED_ICE = BLOCKS.register("slopeobj_frosted_ice", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MAGMA_BLOCK = BLOCKS.register("slopeobj_magma_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_NETHERITE_BLOCK = BLOCKS.register("slopeobj_netherite_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ANCIENT_DEBRIS = BLOCKS.register("slopeobj_ancient_debris", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CRYING_OBSIDIAN = BLOCKS.register("slopeobj_crying_obsidian", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CHISELED_NETHER_BRICKS = BLOCKS.register("slopeobj_chiseled_nether_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CRACKED_NETHER_BRICKS = BLOCKS.register("slopeobj_cracked_nether_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_QUARTZ_BRICKS = BLOCKS.register("slopeobj_quartz_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_AMETHYST_BLOCK = BLOCKS.register("slopeobj_amethyst_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BUDDING_AMETHYST = BLOCKS.register("slopeobj_budding_amethyst", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));

	public static final RegistryObject<Block> SLOPEOBJ_SANDSTONE = BLOCKS.register("slopeobj_sandstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CHISELED_SANDSTONE = BLOCKS.register("slopeobj_chiseled_sandstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CUT_SANDSTONE = BLOCKS.register("slopeobj_cut_sandstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_SANDSTONE = BLOCKS.register("slopeobj_red_sandstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CHISELED_RED_SANDSTONE = BLOCKS.register("slopeobj_chiseled_red_sandstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CUT_RED_SANDSTONE = BLOCKS.register("slopeobj_cut_red_sandstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SMOOTH_SANDSTONE = BLOCKS.register("slopeobj_smooth_sandstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SMOOTH_RED_SANDSTONE = BLOCKS.register("slopeobj_smooth_red_sandstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));

	public static final RegistryObject<Block> SLOPEOBJ_PRISMARINE = BLOCKS.register("slopeobj_prismarine", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PRISMARINE_BRICKS = BLOCKS.register("slopeobj_prismarine_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DARK_PRISMARINE = BLOCKS.register("slopeobj_dark_prismarine", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SEA_LANTERN = BLOCKS.register("slopeobj_sea_lantern", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	
	public static final RegistryObject<Block> SLOPEOBJ_OAK_LEAVES = BLOCKS.register("slopeobj_oak_leaves", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SPRUCE_LEAVES = BLOCKS.register("slopeobj_spruce_leaves", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BIRCH_LEAVES = BLOCKS.register("slopeobj_birch_leaves", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_JUNGLE_LEAVES = BLOCKS.register("slopeobj_jungle_leaves", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ACACIA_LEAVES = BLOCKS.register("slopeobj_acacia_leaves", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DARK_OAK_LEAVES = BLOCKS.register("slopeobj_dark_oak_leaves", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_AZALEA_LEAVES = BLOCKS.register("slopeobj_azalea_leaves", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_FLOWERING_AZALEA_LEAVES = BLOCKS.register("slopeobj_flowering_azalea_leaves", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));

	public static final RegistryObject<Block> SLOPEOBJ_SPONGE = BLOCKS.register("slopeobj_sponge", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_WET_SPONGE = BLOCKS.register("slopeobj_wet_sponge", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_NOTE_BLOCK = BLOCKS.register("slopeobj_note_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SNOW_BLOCK = BLOCKS.register("slopeobj_snow_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CLAY = BLOCKS.register("slopeobj_clay", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_JUKEBOX = BLOCKS.register("slopeobj_jukebox", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PUMPKIN = BLOCKS.register("slopeobj_pumpkin", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GLOWSTONE = BLOCKS.register("slopeobj_glowstone", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CARVED_PUMPKIN = BLOCKS.register("slopeobj_carved_pumpkin", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_JACK_O_LANTERN = BLOCKS.register("slopeobj_jack_o_lantern", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ICE = BLOCKS.register("slopeobj_ice", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BROWN_MUSHROOM_BLOCK = BLOCKS.register("slopeobj_brown_mushroom_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_MUSHROOM_BLOCK = BLOCKS.register("slopeobj_red_mushroom_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MUSHROOM_STEM = BLOCKS.register("slopeobj_mushroom_stem", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MUSHROOM_STEM_M = BLOCKS.register("slopeobj_mushroom_stem_m", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MELON = BLOCKS.register("slopeobj_melon", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_NETHER_WART = BLOCKS.register("slopeobj_nether_wart", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_NETHER_BRICKS = BLOCKS.register("slopeobj_nether_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_REDSTONE_BLOCK = BLOCKS.register("slopeobj_redstone_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SLIME_BLOCK = BLOCKS.register("slopeobj_slime_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_HAY_BLOCK = BLOCKS.register("slopeobj_hay_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_HAY_BLOCK_M = BLOCKS.register("slopeobj_hay_block_m", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_COAL_BLOCK = BLOCKS.register("slopeobj_coal_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PACKED_ICE = BLOCKS.register("slopeobj_packed_ice", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_NETHER_WART_BLOCK = BLOCKS.register("slopeobj_nether_wart_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_NETHER_BRICKS = BLOCKS.register("slopeobj_red_nether_bricks", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BONE_BLOCK = BLOCKS.register("slopeobj_bone_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BONE_BLOCK_M = BLOCKS.register("slopeobj_bone_block_m", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DRIED_KELP_BLOCK = BLOCKS.register("slopeobj_dried_kelp_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLUE_ICE = BLOCKS.register("slopeobj_blue_ice", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_SHROOMLIGHT = BLOCKS.register("slopeobj_shroomlight", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_TARGET = BLOCKS.register("slopeobj_target", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_HONEY_BLOCK = BLOCKS.register("slopeobj_honey_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_HONEYCOMB_BLOCK = BLOCKS.register("slopeobj_honeycomb_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_POWDER_SNOW = BLOCKS.register("slopeobj_powder_snow", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	
	public static final RegistryObject<Block> SLOPEOBJ_TERRACOTTA = BLOCKS.register("slopeobj_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_WHITE_TERRACOTTA = BLOCKS.register("slopeobj_white_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ORANGE_TERRACOTTA = BLOCKS.register("slopeobj_orange_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MAGENTA_TERRACOTTA = BLOCKS.register("slopeobj_magenta_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_BLUE_TERRACOTTA = BLOCKS.register("slopeobj_light_blue_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_YELLOW_TERRACOTTA = BLOCKS.register("slopeobj_yellow_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIME_TERRACOTTA = BLOCKS.register("slopeobj_lime_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PINK_TERRACOTTA = BLOCKS.register("slopeobj_pink_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GRAY_TERRACOTTA = BLOCKS.register("slopeobj_gray_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_GRAY_TERRACOTTA = BLOCKS.register("slopeobj_light_gray_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CYAN_TERRACOTTA = BLOCKS.register("slopeobj_cyan_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PURPLE_TERRACOTTA = BLOCKS.register("slopeobj_purple_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLUE_TERRACOTTA = BLOCKS.register("slopeobj_blue_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BROWN_TERRACOTTA = BLOCKS.register("slopeobj_brown_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GREEN_TERRACOTTA = BLOCKS.register("slopeobj_green_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_TERRACOTTA = BLOCKS.register("slopeobj_red_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLACK_TERRACOTTA = BLOCKS.register("slopeobj_black_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_WHITE_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_white_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ORANGE_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_orange_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MAGENTA_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_magenta_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_BLUE_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_light_blue_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_YELLOW_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_yellow_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIME_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_lime_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PINK_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_pink_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GRAY_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_gray_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_GRAY_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_light_gray_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CYAN_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_cyan_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PURPLE_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_purple_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLUE_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_blue_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BROWN_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_brown_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GREEN_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_green_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_red_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLACK_GLAZED_TERRACOTTA = BLOCKS.register("slopeobj_black_glazed_terracotta", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_WHITE_CONCRETE = BLOCKS.register("slopeobj_white_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ORANGE_CONCRETE = BLOCKS.register("slopeobj_orange_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MAGENTA_CONCRETE = BLOCKS.register("slopeobj_magenta_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_BLUE_CONCRETE = BLOCKS.register("slopeobj_light_blue_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_YELLOW_CONCRETE = BLOCKS.register("slopeobj_yellow_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIME_CONCRETE = BLOCKS.register("slopeobj_lime_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PINK_CONCRETE = BLOCKS.register("slopeobj_pink_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GRAY_CONCRETE = BLOCKS.register("slopeobj_gray_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_GRAY_CONCRETE = BLOCKS.register("slopeobj_light_gray_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CYAN_CONCRETE = BLOCKS.register("slopeobj_cyan_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PURPLE_CONCRETE = BLOCKS.register("slopeobj_purple_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLUE_CONCRETE = BLOCKS.register("slopeobj_blue_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BROWN_CONCRETE = BLOCKS.register("slopeobj_brown_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GREEN_CONCRETE = BLOCKS.register("slopeobj_green_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_CONCRETE = BLOCKS.register("slopeobj_red_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLACK_CONCRETE = BLOCKS.register("slopeobj_black_concrete", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_WHITE_CONCRETE_POWDER = BLOCKS.register("slopeobj_white_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_ORANGE_CONCRETE_POWDER = BLOCKS.register("slopeobj_orange_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_MAGENTA_CONCRETE_POWDER = BLOCKS.register("slopeobj_magenta_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_BLUE_CONCRETE_POWDER = BLOCKS.register("slopeobj_light_blue_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_YELLOW_CONCRETE_POWDER = BLOCKS.register("slopeobj_yellow_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIME_CONCRETE_POWDER = BLOCKS.register("slopeobj_lime_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PINK_CONCRETE_POWDER = BLOCKS.register("slopeobj_pink_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GRAY_CONCRETE_POWDER = BLOCKS.register("slopeobj_gray_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_LIGHT_GRAY_CONCRETE_POWDER = BLOCKS.register("slopeobj_light_gray_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_CYAN_CONCRETE_POWDER = BLOCKS.register("slopeobj_cyan_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_PURPLE_CONCRETE_POWDER = BLOCKS.register("slopeobj_purple_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLUE_CONCRETE_POWDER = BLOCKS.register("slopeobj_blue_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BROWN_CONCRETE_POWDER = BLOCKS.register("slopeobj_brown_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_GREEN_CONCRETE_POWDER = BLOCKS.register("slopeobj_green_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_RED_CONCRETE_POWDER = BLOCKS.register("slopeobj_red_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BLACK_CONCRETE_POWDER = BLOCKS.register("slopeobj_black_concrete_powder", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));

	public static final RegistryObject<Block> SLOPEOBJ_DEAD_TUBE_CORAL_BLOCK = BLOCKS.register("slopeobj_dead_tube_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEAD_BRAIN_CORAL_BLOCK = BLOCKS.register("slopeobj_dead_brain_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEAD_BUBBLE_CORAL_BLOCK = BLOCKS.register("slopeobj_dead_bubble_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEAD_FIRE_CORAL_BLOCK = BLOCKS.register("slopeobj_dead_fire_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_DEAD_HORN_CORAL_BLOCK = BLOCKS.register("slopeobj_dead_horn_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_TUBE_CORAL_BLOCK = BLOCKS.register("slopeobj_tube_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BRAIN_CORAL_BLOCK = BLOCKS.register("slopeobj_brain_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_BUBBLE_CORAL_BLOCK = BLOCKS.register("slopeobj_bubble_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_FIRE_CORAL_BLOCK = BLOCKS.register("slopeobj_fire_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	public static final RegistryObject<Block> SLOPEOBJ_HORN_CORAL_BLOCK = BLOCKS.register("slopeobj_horn_coral_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));
	
	public static final RegistryObject<Block> SLOPEOBJ_OXIDIZED_COPPER = BLOCKS.register("slopeobj_oxidized_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WEATHERED_COPPER = BLOCKS.register("slopeobj_weathered_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_EXPOSED_COPPER = BLOCKS.register("slopeobj_exposed_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_COPPER_BLOCK = BLOCKS.register("slopeobj_copper_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_OXIDIZED_CUT_COPPER = BLOCKS.register("slopeobj_oxidized_cut_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WEATHERED_CUT_COPPER = BLOCKS.register("slopeobj_weathered_cut_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_EXPOSED_CUT_COPPER = BLOCKS.register("slopeobj_exposed_cut_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_CUT_COPPER = BLOCKS.register("slopeobj_cut_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WAXED_COPPER_BLOCK = BLOCKS.register("slopeobj_waxed_copper_block", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WAXED_WEATHERED_COPPER = BLOCKS.register("slopeobj_waxed_weathered_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WAXED_EXPOSED_COPPER = BLOCKS.register("slopeobj_waxed_exposed_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WAXED_OXIDIZED_COPPER = BLOCKS.register("slopeobj_waxed_oxidized_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WAXED_OXIDIZED_CUT_COPPER = BLOCKS.register("slopeobj_waxed_oxidized_cut_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WAXED_WEATHERED_CUT_COPPER = BLOCKS.register("slopeobj_waxed_weathered_cut_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WAXED_EXPOSED_CUT_COPPER = BLOCKS.register("slopeobj_waxed_exposed_cut_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	public static final RegistryObject<Block> SLOPEOBJ_WAXED_CUT_COPPER = BLOCKS.register("slopeobj_waxed_cut_copper", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	
	//public static final RegistryObject<Block> SLOPEOBJ_ = BLOCKS.register("slopeobj_", () -> new SlopeOBJGlassBlock(Blocks.GLASS.defaultBlockState(), properties.Propertiestone()));	

	@SubscribeEvent
	public static void onRegisterItems(final RegistryEvent.Register<Item> event) {
		blockgen.BLOCKS.getEntries().stream().map(RegistryObject::get).forEach(block -> {
			event.getRegistry().register(
					new BlockItem(block, new Item.Properties().tab(tablist.SCTAB_MAIN)).setRegistryName(block.getRegistryName()));
		});	}
}
